### ISSUE TITLE
Braces Style

### ISSUE THREAD

**Issue by ervannur** [greenoss/Coding-Standards#1]
About braces style in [here](https://github.com/greenoss/Coding-Standards/tree/master/wp/coding-style-guide#braces-style) I consider to remove this style
```
// simple conditional with single statement (be careful!)
if (condition)
       // code
```

I think this style has higher chance to make error. If there are some line under the condition, the code will unclear as a part of conditional or not

**Comment by greenoss** [comment]
Hey @ervannur ,
Good point. I agree that style could lead into:

- higher chance to make error
- unclear readibility

I will remove this condition style

**Comment by greenoss** [comment]
This variation is disallowed by now. Thank you Ervan!

https://github.com/greenoss/Coding-Standards/tree/master/wp/coding-style-guide#braces-style
